<a href="https://colab.research.google.com/github/nohjuhyeon/study_AIs/blob/main/docs/quests/MLs/SpineSurgeryList_FeatureEngin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 지도학습 - 분류형
- target 기준 이항, 다항으로 나눔

In [1]:
import pandas as pd
df_SSL = pd.read_csv("SpineSurgeryList.csv")
df_SSL

Unnamed: 0    환자ID  Large Lymphocyte  Location of herniation   ODI  가족력  \
0              0     1PT              22.8                       3  51.0  0.0   
1              1     2PT              44.9                       4  26.0  0.0   
2              2     3PT              53.0                       3   NaN  0.0   
3              3     4PT              54.7                       4  18.0  0.0   
4              4     5PT              53.8                       4   NaN  0.0   
...          ...     ...               ...                     ...   ...  ...   
1889        1889  1890PT              44.0                       1   NaN  0.0   
1890        1890  1891PT              30.8                       2   NaN  0.0   
1891        1891  1892PT              36.7                       3   NaN  0.0   
1892        1892  1893PT              32.5                       2   NaN  0.0   
1893        1893  1894PT              49.5                       2   NaN  0.0   

      간질성폐질환  고혈압여부  과거수술횟수  당뇨여부  ...  Modic change    PI    PT  \
0          0      0       0     0  ...             3  51.6  36.6   
1          0      0       0     0  ...             0  40.8   7.2   
2          0      0       1     0  ...             0  67.5  27.3   
3          0      1       0     0  ...             0  49.2  18.7   
4          0      1       0     0  ...             0  58.8  14.7   
...      ...    ...     ...   ...  ...           ...   ...   ...   
1889       0      0       0     0  ...             2  59.5  23.0   
1890       0      0       0     0  ...             0  47.7  20.2   
1891       0      0       0     0  ...             0  44.6  15.0   
1892       0      0       0     0  ...             2  32.2  11.1   
1893       0      0       0     0  ...             0  38.9   6.8   

      Seg Angle(raw)  Vaccum disc   골밀도   디스크단면적  디스크위치  척추이동척도  척추전방위증  
0               14.4            0 -1.01  2048.50      4    Down       0  
1               17.8            0 -1.14  1753.10      4      Up       0  
2               10.2            0 -1.77  1749.00      4    Down       0  
3               19.9            0 -1.58  1796.20      4    Down       0  
4                5.2            0 -0.79  2021.48      4      Up       0  
...              ...          ...   ...      ...    ...     ...     ...  
1889            21.8            0   NaN  2652.20      5  Middle       0  
1890             5.0            0   NaN  1795.80      4    Down       0  
1891            17.4            1   NaN  2624.40      4    Down       0  
1892            17.7            0   NaN  1972.50      5    Down       0  
1893            27.8            0   NaN  1574.40      5  Middle       0  

[1894 rows x 52 columns]

In [2]:
df_SSL = df_SSL.rename(columns={'Location of herniation': 'Location_of_herniation'})
df_SSL = df_SSL.rename(columns={'Vaccum disc': 'Vaccum_disc'})

In [3]:
df_SSL['지방축적도'].value_counts()

177.30    8
122.00    7
127.10    7
111.50    6
137.60    6
         ..
113.00    1
116.81    1
212.87    1
100.74    1
251.40    1
Name: 지방축적도, Length: 878, dtype: int64

In [4]:
df_SSL['BMI'] = df_SSL['체중']/((df_SSL['신장']*0.01)**2)

In [5]:
df_SSL.isnull().sum()

Unnamed: 0                   0
환자ID                         0
Large Lymphocyte             0
Location_of_herniation       0
ODI                       1432
가족력                         51
간질성폐질환                       0
고혈압여부                        0
과거수술횟수                       0
당뇨여부                         0
말초동맥질환여부                     0
빈혈여부                         0
성별                           0
스테로이드치료                      0
신부전여부                        0
신장                           0
심혈관질환                        0
암발병여부                        0
연령                           0
우울증여부                        0
입원기간                         0
입원일자                         0
종양진행여부                       0
직업                         415
체중                           0
퇴원일자                         0
헤모글로빈수치                      1
혈전합병증여부                      0
환자통증정도                       0
흡연여부                         0
통증기간(월)                      4
수술기법                        81
수술시간    

In [6]:
df_SSL.columns

Index(['Unnamed: 0', '환자ID', 'Large Lymphocyte', 'Location_of_herniation',
       'ODI', '가족력', '간질성폐질환', '고혈압여부', '과거수술횟수', '당뇨여부', '말초동맥질환여부', '빈혈여부',
       '성별', '스테로이드치료', '신부전여부', '신장', '심혈관질환', '암발병여부', '연령', '우울증여부', '입원기간',
       '입원일자', '종양진행여부', '직업', '체중', '퇴원일자', '헤모글로빈수치', '혈전합병증여부', '환자통증정도',
       '흡연여부', '통증기간(월)', '수술기법', '수술시간', '수술실패여부', '수술일자', '재발여부', '혈액형',
       '전방디스크높이(mm)', '후방디스크높이(mm)', '지방축적도', 'Instability', 'MF + ES',
       'Modic change', 'PI', 'PT', 'Seg Angle(raw)', 'Vaccum_disc', '골밀도',
       '디스크단면적', '디스크위치', '척추이동척도', '척추전방위증', 'BMI'],
      dtype='object')

In [7]:
df_SSL_extract = df_SSL.loc[:,['재발여부','Vaccum_disc','Location_of_herniation','디스크단면적','연령','BMI','통증기간(월)', '지방축적도']]
df_SSL_extract.isnull().sum()

재발여부                      0
Vaccum_disc               0
Location_of_herniation    0
디스크단면적                    1
연령                        0
BMI                       0
통증기간(월)                   4
지방축적도                     3
dtype: int64

## 데이터
- 목표변수(target) : '재발여부'
- 설명변수 (feature)
  - 범주형 : 'Vaccum_disc','Location_of_herniation'
  - 수치형 : '디스크단면적','연령','BMI','통증기간(월)', '지방축적도'

In [8]:
df_SSL_extract['재발여부'].unique()

array([0, 1])

In [9]:
df_SSL_extract= df_SSL_extract.dropna()
df_SSL_extract.isnull().sum()

재발여부                      0
Vaccum_disc               0
Location_of_herniation    0
디스크단면적                    0
연령                        0
BMI                       0
통증기간(월)                   0
지방축적도                     0
dtype: int64

In [10]:
df_SSL_extract[:2]

재발여부  Vaccum_disc  Location_of_herniation  디스크단면적  연령        BMI  통증기간(월)  \
0     0            0                       3  2048.5  66  22.695623      1.0   
1     0            0                       4  1753.1  47  24.520365      1.0   

   지방축적도  
0  282.3  
1  177.3

## 특성공학(Feature Engineering)
- 수치 평준화 : 수치형과 범주형 각각 적용
- 개수 균형화 : target 수량 균형화

### Scaling 수치형에 적용
- Standard Scaling : 평균 0, 표준편차 1
- Min-Max Scaling : 0-1 사이
- Robust Scaling : 이상치가 많은 데이터 셋(중앙값 기준)

In [11]:
from sklearn.preprocessing import MinMaxScaler
def minmaxscaler_func(x):
  minMaxScaler = MinMaxScaler()
  minMaxScaler.fit(x)
  return minMaxScaler.transform(x)
  # '디스크단면적','연령','BMI','통증기간(월)', '지방축적도'

In [12]:
df_SSL_extract['디스크단면적']= minmaxscaler_func(df_SSL_extract['디스크단면적'].values.reshape(-1,1))
df_SSL_extract['디스크단면적'].describe() # min-max 가 0-1 사이

count    1886.000000
mean        0.407261
std         0.151610
min         0.000000
25%         0.304547
50%         0.404274
75%         0.498327
max         1.000000
Name: 디스크단면적, dtype: float64

In [13]:
df_SSL_extract['연령']= minmaxscaler_func(df_SSL_extract['연령'].values.reshape(-1,1))
df_SSL_extract['연령'].describe() # min-max 가 0-1 사이

count    1886.000000
mean        0.372664
std         0.189252
min         0.000000
25%         0.239437
50%         0.366197
75%         0.478873
max         1.000000
Name: 연령, dtype: float64

In [14]:
df_SSL_extract['BMI']= minmaxscaler_func(df_SSL_extract['BMI'].values.reshape(-1,1))
df_SSL_extract['BMI'].describe() # min-max 가 0-1 사이

count    1886.000000
mean        0.283273
std         0.083892
min         0.000000
25%         0.235722
50%         0.287006
75%         0.310846
max         1.000000
Name: BMI, dtype: float64

In [15]:
df_SSL_extract['통증기간(월)']= minmaxscaler_func(df_SSL_extract['통증기간(월)'].values.reshape(-1,1))
df_SSL_extract['통증기간(월)'].describe() # min-max 가 0-1 사이

count    1886.000000
mean        0.016357
std         0.047942
min         0.000000
25%         0.002778
50%         0.005556
75%         0.011111
max         1.000000
Name: 통증기간(월), dtype: float64

In [16]:
df_SSL_extract['지방축적도']= minmaxscaler_func(df_SSL_extract['지방축적도'].values.reshape(-1,1))
df_SSL_extract['지방축적도'].describe() # min-max 가 0-1 사이

count    1886.000000
mean        0.017847
std         0.036878
min         0.000000
25%         0.007882
50%         0.011844
75%         0.018683
max         1.000000
Name: 지방축적도, dtype: float64

### Onehot encoding : 범주형에 적용

In [17]:
df_SSL_extract['Location_of_herniation'].unique()

array([3, 4, 2, 5, 1])

In [18]:
from sklearn.preprocessing import OneHotEncoder
def onehot_encoding_func(x):
  oneHotEncoder_x =OneHotEncoder()
  oneHotEncoder_x.fit(x)
  encoder_x = oneHotEncoder_x.transform(x).toarray()
  df_encoder_x = pd.DataFrame(data=encoder_x,columns=oneHotEncoder_x.get_feature_names_out())
  return df_encoder_x

In [19]:
df_encoder_LOH = onehot_encoding_func(df_SSL_extract[['Location_of_herniation']])
df_encoder_VD = onehot_encoding_func(df_SSL_extract[['Vaccum_disc']])

In [20]:
# 행으로 concate
df_SSL_extract = pd.concat((df_SSL_extract.reset_index(drop=True),df_encoder_LOH.reset_index(drop=True),df_encoder_VD.reset_index(drop=True)),axis=1)
# df_TFD_extract[:2]
df_SSL_extract.shape

(1886, 15)

## 모델

### 정형화 단계 - target과 feature 분리

In [21]:
target_train = df_SSL_extract['재발여부']
feature_train = df_SSL_extract.drop(columns=['재발여부'])
target_train.shape, feature_train.shape

((1886,), (1886, 14))

In [22]:
feature_train

Vaccum_disc  Location_of_herniation    디스크단면적        연령       BMI  \
0               0                       3  0.436424  0.718310  0.243499   
1               0                       4  0.293609  0.450704  0.297579   
2               0                       3  0.291626  0.338028  0.292057   
3               0                       4  0.314446  0.352113  0.297208   
4               0                       4  0.423361  0.380282  0.285045   
...           ...                     ...       ...       ...       ...   
1881            0                       1  0.728292  0.619718  0.340380   
1882            0                       2  0.314253  0.380282  0.280262   
1883            1                       3  0.714852  0.647887  0.314743   
1884            0                       2  0.399681  0.197183  0.299283   
1885            0                       2  0.207213  0.211268  0.085402   

       통증기간(월)     지방축적도  Location_of_herniation_1  Location_of_herniation_2  \
0     0.002778  0.021206                       0.0                       0.0   
1     0.002778  0.012520                       0.0                       0.0   
2     0.002778  0.019097                       0.0                       0.0   
3     0.005556  0.018542                       0.0                       0.0   
4     0.002778  0.017061                       0.0                       0.0   
...        ...       ...                       ...                       ...   
1881  0.033333  0.017500                       1.0                       0.0   
1882  0.016667  0.021678                       0.0                       1.0   
1883  0.002778  0.010137                       0.0                       0.0   
1884  0.066667  0.005214                       0.0                       1.0   
1885  0.016667  0.018650                       0.0                       1.0   

      Location_of_herniation_3  Location_of_herniation_4  \
0                          1.0                       0.0   
1                          0.0                       1.0   
2                          1.0                       0.0   
3                          0.0                       1.0   
4                          0.0                       1.0   
...                        ...                       ...   
1881                       0.0                       0.0   
1882                       0.0                       0.0   
1883                       1.0                       0.0   
1884                       0.0                       0.0   
1885                       0.0                       0.0   

      Location_of_herniation_5  Vaccum_disc_0  Vaccum_disc_1  
0                          0.0            1.0            0.0  
1                          0.0            1.0            0.0  
2                          0.0            1.0            0.0  
3                          0.0            1.0            0.0  
4                          0.0            1.0            0.0  
...                        ...            ...            ...  
1881                       0.0            1.0            0.0  
1882                       0.0            1.0            0.0  
1883                       0.0            0.0            1.0  
1884                       0.0            1.0            0.0  
1885                       0.0            1.0            0.0  

[1886 rows x 14 columns]

In [23]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model

LogisticRegression()

In [24]:
model.fit(feature_train,target_train)

LogisticRegression()

In [25]:
model.coef_,model.intercept_ # y = -1.22653571x_1(Pclass) + -0.04149665x_2(Age) + 3.532956

(array([[ 0.01667032,  0.07535656,  0.77627124,  0.50628405,  3.71082857,
          1.20248957, -0.03629689, -0.15447517,  0.14910943,  0.15753117,
         -0.22259064,  0.06987638, -0.01721915,  0.01667032]]),
 array([-3.83319871]))

## 평가

In [30]:
model.predict(feature_train)

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
model.predict_proba(feature_train) # 확률값

array([[0.86508815, 0.13491185],
       [0.90099491, 0.09900509],
       [0.87898753, 0.12101247],
       ...,
       [0.79614872, 0.20385128],
       [0.87544004, 0.12455996],
       [0.95009803, 0.04990197]])

### 평가 수치
- 정확도
-

In [28]:
# 정확도
from sklearn.metrics import accuracy_score
target_train_predict = model.predict(feature_train)
target_train_predict.shape, target_train.shape

((1886,), (1886,))

In [29]:
accuracy_score(target_train, target_train_predict)

0.88016967126193